
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 71
#define YY_END_OF_BUFFER 72
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[213] =
    {   0,
       45,   45,    0,    0,    0,    0,   72,   70,   58,   59,
       70,   64,   70,   47,   48,   41,   39,   51,   50,   45,
       45,   53,   49,   38,   52,   38,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   54,   55,   61,   67,   67,   67,   65,
       69,   71,   63,   71,   62,   60,    0,    0,    0,   57,
       46,   46,    0,    0,    0,    0,   45,    0,   56,   38,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   21,
       44,   44,   44,   44,   44,   17,   43,   44,   44,    6,
       40,   44,   44,   44,   44,   24,   44,   44,   44,   44,

       44,   44,   68,   67,   66,   67,   63,   31,   30,    0,
        0,    0,    0,    0,    0,   46,   46,   46,   46,   45,
       46,   45,    0,    0,    0,   46,   41,   44,   44,   44,
       44,   44,   41,   44,   44,   16,   44,   22,   44,   44,
       41,   42,   44,   44,    5,   44,   44,   44,    7,   44,
       44,   44,   36,   33,   32,   35,   34,   37,   46,   45,
       45,   44,   44,   44,   14,   44,   44,   19,   44,   44,
       44,   44,   44,   44,   26,   12,   18,   28,    3,   44,
       25,   44,    4,   15,   44,    2,   44,   29,   44,   44,
       44,   44,   44,   20,   27,   44,   23,   44,   44,   44,

       44,   44,   13,    8,   44,   11,   44,    1,    9,   44,
       10,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    6,    6,    6,    6,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    6,    6,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   34,   35,   36,   37,   38,   39,
       34,   40,   41,   42,   43,   44,   45,   34,   46,   34,
       47,   48,   49,    6,   50,    6,   51,   52,   53,   54,

       55,   56,   57,   58,   59,   34,   34,   60,   61,   62,
       63,   64,   34,   65,   66,   67,   68,   69,   70,   34,
       71,   34,   72,    6,   73,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[74] =
    {   0,
        1,    1,    1,    1,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    3,    2,    4,    4,    4,    2,
        2,    2,    2,    2,    4,    4,    4,    4,    4,    4,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    2,    2,    2,    5,
        4,    4,    4,    4,    4,    4,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    2,    2
    } ;

static const flex_int16_t yy_base[222] =
    {   0,
        0,    0,   71,   73,   78,   80,  232, 1040, 1040, 1040,
      226, 1040,  149, 1040, 1040, 1040, 1040, 1040,   70,   75,
       80,  202, 1040,   79, 1040,  201,  112,   87,  149,  167,
      171,  176,   93,  198,  185,  219,  223,  228,  232,  247,
      286,  255,  252, 1040, 1040, 1040, 1040, 1040,  217, 1040,
      110, 1040, 1040,  210, 1040, 1040,  183,  126,  350, 1040,
      105,  272,  119,  126,  100,  111,  279,  295, 1040, 1040,
        0,  129,  302,  319,  161,  322,  328,  345,  349,  352,
      355,  381,  406,  386,  410,  192,  413,  420,  425,  435,
      439,  443,  446,  451,  458,  465,  471,  477,  481,  484,

      490,  493, 1040, 1040, 1040,  129, 1040, 1040, 1040,  112,
      109,  100,   92,   88,   83,  505,  511,  516,  122,  241,
        0,   71,  532,  541,  519,  536,  545,  550,  555,  559,
      562,  565,  572,  580,  586,  590,  593,  603,  611,  606,
      626,  632,  635,  639,  651,  658,  661,  667,  664,  683,
      687,  690, 1040, 1040, 1040, 1040, 1040, 1040,  158,  165,
       64,  693,  696,  706,  709,  712,  723,  719,  730,  749,
      734,  752,  763,  770,  776,  779,  785,  788,  794,  797,
      802,  805,  810,  813,  819,  822,  828,  831,  836,  839,
      844,  850,  862,  865,  871,  875,  878,  888,  891,  900,

      903,  907,  913,  916,  930,  933,  938,  941,  944,  955,
      958, 1040, 1010, 1015, 1019, 1021, 1026, 1029, 1030, 1033,
     1035
    } ;

static const flex_int16_t yy_def[222] =
    {   0,
      212,    1,  213,  213,  214,  214,  212,  212,  212,  212,
      212,  212,  215,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  212,  212,  212,  212,  212,  212,  212,
      217,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  218,  212,  212,  212,  212,
      219,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,

      216,  216,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      220,  221,  212,  212,  212,  212,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  212,  212,  212,  212,  212,  212,  212,  212,
      221,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,

      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,    0,  212,  212,  212,  212,  212,  212,  212,  212,
      212
    } ;

static const flex_int16_t yy_nxt[1114] =
    {   0,
        8,    9,   10,   11,    9,    8,   12,   13,   14,   15,
       16,   17,   18,   17,   19,   16,   20,   21,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   33,   34,   33,   33,   35,   36,   37,   38,   39,
       40,   41,   33,   42,   43,   33,   44,    8,   45,   33,
       27,   28,   29,   30,   31,   32,   33,   33,   34,   33,
       35,   36,   37,   38,   39,   40,   41,   33,   42,   43,
       33,   46,    8,   48,   49,   48,   49,   50,  121,   50,
       53,   54,   53,   54,   60,  121,   61,   62,   62,   63,
      158,   64,   64,   64,   63,  157,   67,   67,   67,  156,

       65,   70,   70,   71,   71,   71,   66,  155,   68,   71,
       71,   71,  105,  106,  119,   75,  154,  120,   51,  153,
       51,   61,  116,  116,   76,  121,   65,  121,   71,   71,
       71,  105,   66,  109,   68,   61,   61,   61,  159,  159,
       63,   75,   64,   64,   64,   71,   71,   71,   73,   76,
       55,   74,   55,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   71,   71,   71,   57,   57,
       57,   57,   57,   73,  159,  159,   74,   71,   71,   71,
       77,  160,  160,   71,   71,   71,   78,   71,   71,   71,
      108,  129,   71,   71,   71,   57,   59,   57,   57,   79,

       83,   71,   71,   71,   80,   81,   77,   82,   71,   71,
       71,   78,  107,   84,   71,   71,   71,  129,   85,  103,
       57,   57,   88,   70,   69,   79,   83,   86,   56,   80,
       81,  212,   82,  212,   87,   71,   71,   71,   84,   71,
       71,   71,  212,   85,   71,   71,   71,   88,   71,   71,
       71,  212,   90,   86,  212,  119,   89,  160,  160,   87,
       93,  212,   91,   71,   71,   71,  212,   92,   71,   71,
       71,   71,   71,   71,  212,   94,  212,  212,   90,   99,
      212,   89,  212,  100,  101,  212,   93,   91,  117,  118,
      118,  102,   92,   63,  212,  123,  124,  124,  212,  212,

       68,   94,   71,   71,   71,   99,  125,   68,  125,  100,
      101,  126,  126,  126,  212,  212,  102,   95,   71,   71,
       71,  212,  212,   96,  212,   97,   68,  212,  212,  127,
      212,   98,  212,   68,  212,   71,   71,   71,   71,   71,
       71,  212,  212,   95,   71,   71,   71,  212,   96,  212,
       97,  212,  131,  212,  212,  127,   98,  108,  128,  130,
      212,   71,   71,   71,  212,   71,   71,   71,   71,   71,
       71,   71,   71,   71,  212,  110,  212,  212,  131,  111,
      212,  132,  212,  128,  130,  212,  112,  212,  212,  113,
      212,  114,  133,  115,  212,  135,  134,   71,   71,   71,

      212,  110,   71,   71,   71,  111,  132,  212,  136,  212,
      212,  112,  212,  212,  113,  212,  114,  133,  115,  212,
      135,  134,   71,   71,   71,  138,   71,   71,   71,   71,
       71,   71,  212,  212,  136,  212,   71,   71,   71,  212,
      137,   71,   71,   71,  212,  212,  139,  141,  212,  212,
      138,   71,   71,   71,  140,   71,   71,   71,  212,   71,
       71,   71,   71,   71,   71,  137,  142,   71,   71,   71,
      144,  139,  212,  141,   71,   71,   71,  212,  212,  140,
      143,   71,   71,   71,  212,  212,  146,   71,   71,   71,
      212,  142,  145,   71,   71,   71,  144,   71,   71,   71,

       71,   71,   71,  212,  212,  143,   71,   71,   71,   71,
       71,   71,  146,  147,  212,  148,  150,  145,  212,  212,
      149,   61,  116,  116,  212,  152,  212,  117,  118,  118,
      212,  151,  117,  118,  118,  126,  126,  126,  147,   68,
      148,  212,  150,  212,   68,  149,   63,  212,  123,  123,
      123,  152,  126,  126,  126,   63,  151,   67,   67,   67,
       68,   71,   71,   71,  212,   68,   71,   71,   71,   68,
       68,   71,   71,   71,  162,   71,   71,   71,   71,   71,
       71,   71,   71,   71,  212,  212,   68,  163,   71,   71,
       71,  212,  212,  164,  212,   68,   71,   71,   71,  212,

      162,  165,   71,   71,   71,  166,   71,   71,   71,   71,
       71,   71,  212,  163,  168,  212,  167,  212,  164,   71,
       71,   71,   71,   71,   71,  212,  165,   71,   71,   71,
      166,  212,  212,  169,  172,  212,  212,  171,  212,  212,
      168,  167,   71,   71,   71,  212,  212,  170,   71,   71,
       71,   71,   71,   71,  212,   71,   71,   71,  169,  212,
      172,  173,  212,  171,  212,  174,  175,   71,   71,   71,
      212,  212,  170,  176,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,  212,  173,  212,  178,
      212,  174,  175,  212,  177,  179,  212,  212,  176,   71,

       71,   71,  212,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,  178,  212,  180,  181,  177,
      212,  179,   71,   71,   71,   71,   71,   71,   71,   71,
       71,  182,  184,  212,  185,   71,   71,   71,  183,   71,
       71,   71,  180,  212,  181,  212,   71,   71,   71,  212,
       71,   71,   71,  186,  212,  212,  182,  184,  188,  212,
      185,  212,  212,  183,  187,   71,   71,   71,   71,   71,
       71,  212,  212,  189,  212,  190,  212,  212,  186,   71,
       71,   71,  191,  212,  188,  212,   71,   71,   71,  187,
      212,  192,   71,   71,   71,   71,   71,   71,  212,  189,

      190,   71,   71,   71,   71,   71,   71,  212,  191,  193,
       71,   71,   71,   71,   71,   71,  212,  192,   71,   71,
       71,   71,   71,   71,  212,  194,   71,   71,   71,   71,
       71,   71,  212,  195,  193,   71,   71,   71,   71,   71,
       71,  212,  212,  196,   71,   71,   71,   71,   71,   71,
      212,  194,   71,   71,   71,   71,   71,   71,  212,  195,
       71,   71,   71,  212,  212,  197,   71,   71,   71,  196,
      212,  199,  200,  212,  212,  198,  212,  201,   71,   71,
       71,   71,   71,   71,  212,  212,  202,   71,   71,   71,
      197,   71,   71,   71,   71,   71,   71,  199,  200,  212,

      198,  212,  212,  201,   71,   71,   71,   71,   71,   71,
      212,  203,  202,  212,  212,  204,   71,   71,   71,   71,
       71,   71,  212,   71,   71,   71,  212,  212,  205,   71,
       71,   71,   71,   71,   71,  212,  203,  212,  212,  206,
      212,  204,  208,  212,  212,  207,   71,   71,   71,   71,
       71,   71,  212,  205,   71,   71,   71,   71,   71,   71,
       71,   71,   71,  212,  206,  212,  209,  208,  212,  212,
      207,   71,   71,   71,   71,   71,   71,  210,  212,  212,
      212,  212,  212,  211,  212,  212,  212,  212,  212,  212,
      212,  209,  212,  212,  212,  212,  212,  212,  212,  212,

      212,  212,  210,  212,  212,  212,  212,  212,  212,  211,
       47,   47,   47,   47,   47,   52,   52,   52,   52,   52,
       58,   58,   58,   58,   72,   72,  104,  104,  104,  104,
      104,  122,  122,   71,   71,  121,  121,  161,  161,    7,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,

      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212
    } ;

static const flex_int16_t yy_chk[1114] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    4,    4,    3,  161,    4,
        5,    5,    6,    6,   19,  122,   19,   19,   19,   20,
      115,   20,   20,   20,   21,  114,   21,   21,   21,  113,

       20,   24,   24,   28,   28,   28,   20,  112,   21,   33,
       33,   33,   51,   51,   65,   28,  111,   65,    3,  110,
        4,   61,   61,   61,   28,   66,   20,   66,   27,   27,
       27,  106,   20,   58,   21,   63,   63,   63,  119,  119,
       64,   28,   64,   64,   64,   72,   72,   72,   27,   28,
        5,   27,    6,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   29,   29,   29,   13,   13,
       13,   13,   13,   27,  159,  159,   27,   75,   75,   75,
       29,  160,  160,   30,   30,   30,   29,   31,   31,   31,
       57,   75,   32,   32,   32,   13,   13,   13,   13,   30,

       32,   35,   35,   35,   30,   31,   29,   31,   86,   86,
       86,   29,   54,   32,   34,   34,   34,   75,   32,   49,
       13,   13,   35,   26,   22,   30,   32,   34,   11,   30,
       31,    7,   31,    0,   34,   36,   36,   36,   32,   37,
       37,   37,    0,   32,   38,   38,   38,   35,   39,   39,
       39,    0,   37,   34,    0,  120,   36,  120,  120,   34,
       39,    0,   37,   40,   40,   40,    0,   38,   43,   43,
       43,   42,   42,   42,    0,   40,    0,    0,   37,   42,
        0,   36,    0,   43,   43,    0,   39,   37,   62,   62,
       62,   43,   38,   67,    0,   67,   67,   67,    0,    0,

       62,   40,   41,   41,   41,   42,   68,   67,   68,   43,
       43,   68,   68,   68,    0,    0,   43,   41,   73,   73,
       73,    0,    0,   41,    0,   41,   62,    0,    0,   73,
        0,   41,    0,   67,    0,   74,   74,   74,   76,   76,
       76,    0,    0,   41,   77,   77,   77,    0,   41,    0,
       41,    0,   77,    0,    0,   73,   41,   59,   74,   76,
        0,   78,   78,   78,    0,   79,   79,   79,   80,   80,
       80,   81,   81,   81,    0,   59,    0,    0,   77,   59,
        0,   78,    0,   74,   76,    0,   59,    0,    0,   59,
        0,   59,   79,   59,    0,   81,   80,   82,   82,   82,

        0,   59,   84,   84,   84,   59,   78,    0,   82,    0,
        0,   59,    0,    0,   59,    0,   59,   79,   59,    0,
       81,   80,   83,   83,   83,   84,   85,   85,   85,   87,
       87,   87,    0,    0,   82,    0,   88,   88,   88,    0,
       83,   89,   89,   89,    0,    0,   85,   88,    0,    0,
       84,   90,   90,   90,   87,   91,   91,   91,    0,   92,
       92,   92,   93,   93,   93,   83,   89,   94,   94,   94,
       93,   85,    0,   88,   95,   95,   95,    0,    0,   87,
       92,   96,   96,   96,    0,    0,   95,   97,   97,   97,
        0,   89,   94,   98,   98,   98,   93,   99,   99,   99,

      100,  100,  100,    0,    0,   92,  101,  101,  101,  102,
      102,  102,   95,   97,    0,   98,  100,   94,    0,    0,
       99,  116,  116,  116,    0,  102,    0,  117,  117,  117,
        0,  101,  118,  118,  118,  125,  125,  125,   97,  117,
       98,    0,  100,    0,  118,   99,  123,    0,  123,  123,
      123,  102,  126,  126,  126,  124,  101,  124,  124,  124,
      123,  127,  127,  127,    0,  117,  128,  128,  128,  124,
      118,  129,  129,  129,  128,  130,  130,  130,  131,  131,
      131,  132,  132,  132,    0,    0,  123,  129,  133,  133,
      133,    0,    0,  130,    0,  124,  134,  134,  134,    0,

      128,  131,  135,  135,  135,  132,  136,  136,  136,  137,
      137,  137,    0,  129,  135,    0,  134,    0,  130,  138,
      138,  138,  140,  140,  140,    0,  131,  139,  139,  139,
      132,    0,    0,  137,  140,    0,    0,  139,    0,    0,
      135,  134,  141,  141,  141,    0,    0,  138,  142,  142,
      142,  143,  143,  143,    0,  144,  144,  144,  137,    0,
      140,  143,    0,  139,    0,  143,  144,  145,  145,  145,
        0,    0,  138,  144,  146,  146,  146,  147,  147,  147,
      149,  149,  149,  148,  148,  148,    0,  143,    0,  147,
        0,  143,  144,    0,  146,  148,    0,    0,  144,  150,

      150,  150,    0,  151,  151,  151,  152,  152,  152,  162,
      162,  162,  163,  163,  163,  147,    0,  150,  151,  146,
        0,  148,  164,  164,  164,  165,  165,  165,  166,  166,
      166,  152,  163,    0,  164,  168,  168,  168,  162,  167,
      167,  167,  150,    0,  151,    0,  169,  169,  169,    0,
      171,  171,  171,  166,    0,    0,  152,  163,  169,    0,
      164,    0,    0,  162,  167,  170,  170,  170,  172,  172,
      172,    0,    0,  170,    0,  171,    0,    0,  166,  173,
      173,  173,  172,    0,  169,    0,  174,  174,  174,  167,
        0,  173,  175,  175,  175,  176,  176,  176,    0,  170,

      171,  177,  177,  177,  178,  178,  178,    0,  172,  174,
      179,  179,  179,  180,  180,  180,    0,  173,  181,  181,
      181,  182,  182,  182,    0,  180,  183,  183,  183,  184,
      184,  184,    0,  182,  174,  185,  185,  185,  186,  186,
      186,    0,    0,  185,  187,  187,  187,  188,  188,  188,
        0,  180,  189,  189,  189,  190,  190,  190,    0,  182,
      191,  191,  191,    0,    0,  187,  192,  192,  192,  185,
        0,  190,  191,    0,    0,  189,    0,  192,  193,  193,
      193,  194,  194,  194,    0,    0,  193,  195,  195,  195,
      187,  196,  196,  196,  197,  197,  197,  190,  191,    0,

      189,    0,    0,  192,  198,  198,  198,  199,  199,  199,
        0,  196,  193,    0,    0,  198,  200,  200,  200,  201,
      201,  201,    0,  202,  202,  202,    0,    0,  199,  203,
      203,  203,  204,  204,  204,    0,  196,    0,    0,  200,
        0,  198,  202,    0,    0,  201,  205,  205,  205,  206,
      206,  206,    0,  199,  207,  207,  207,  208,  208,  208,
      209,  209,  209,    0,  200,    0,  205,  202,    0,    0,
      201,  210,  210,  210,  211,  211,  211,  207,    0,    0,
        0,    0,    0,  210,    0,    0,    0,    0,    0,    0,
        0,  205,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,  207,    0,    0,    0,    0,    0,    0,  210,
      213,  213,  213,  213,  213,  214,  214,  214,  214,  214,
      215,  215,  215,  215,  216,  216,  217,  217,  217,  217,
      217,  218,  218,  219,  219,  220,  220,  221,  221,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,

      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[72] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "compiler.l"
#line 2 "compiler.l"
    // #include "token.h"  The previous tokens used for the execution of Flex
    #include "compiler.tab.h"
    #include <stdio.h>
    #include <stdlib.h>
    #include <math.h>
    #include <string.h>
    #include <unistd.h>

    int errorCnt = 0;
    int lineno = 1;
    char str_buf[256];

    void PRINT_TOK(int token_id);
    int BINHEX_TO_INT(char *str);
    float FBINHEX_TO_FLOAT(char *str);
#line 809 "lex.yy.c"

/*Assigning Regular Expressions*/
#line 812 "lex.yy.c"

#define INITIAL 0
#define PSTRING 1
#define COMMENTS 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 48 "compiler.l"

#line 1033 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 213 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1040 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 49 "compiler.l"
{PRINT_TOK(P_PROGRAM); return P_PROGRAM;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 50 "compiler.l"
{PRINT_TOK(P_CONST); return P_CONST;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 51 "compiler.l"
{PRINT_TOK(P_TYPE); return P_TYPE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 52 "compiler.l"
{PRINT_TOK(P_SET); return P_SET;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 53 "compiler.l"
{PRINT_TOK(P_OF); return P_OF;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 54 "compiler.l"
{PRINT_TOK(P_RECORD); return P_RECORD;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 55 "compiler.l"
{PRINT_TOK(P_VAR); return P_VAR;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 56 "compiler.l"
{PRINT_TOK(P_FORWARD); return P_FORWARD;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 57 "compiler.l"
{PRINT_TOK(P_FUNCTION); return P_FUNCTION;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 58 "compiler.l"
{PRINT_TOK(P_PROCEDURE); return P_PROCEDURE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 59 "compiler.l"
{PRINT_TOK(P_INTEGER); return P_INTEGER;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 60 "compiler.l"
{PRINT_TOK(P_REAL); return P_REAL;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 61 "compiler.l"
{PRINT_TOK(P_BOOLEAN); return P_BOOLEAN;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 62 "compiler.l"
{PRINT_TOK(P_CHAR); return P_CHAR;}                  
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 63 "compiler.l"
{PRINT_TOK(P_BEGIN); return P_BEGIN;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 64 "compiler.l"
{PRINT_TOK(P_END); return P_END;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 65 "compiler.l"
{PRINT_TOK(P_IF); return P_IF;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 66 "compiler.l"
{PRINT_TOK(P_THEN); return P_THEN;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 67 "compiler.l"
{PRINT_TOK(P_ELSE); return P_ELSE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 68 "compiler.l"
{PRINT_TOK(P_WHILE); return P_WHILE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 69 "compiler.l"
{PRINT_TOK(P_DO); return P_DO;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 70 "compiler.l"
{PRINT_TOK(P_FOR); return P_FOR;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 71 "compiler.l"
{PRINT_TOK(P_DOWNTO); return P_DOWNTO;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 72 "compiler.l"
{PRINT_TOK(P_TO); return P_TO;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 73 "compiler.l"
{PRINT_TOK(P_WITH); return P_WITH;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 74 "compiler.l"
{PRINT_TOK(P_READ); return P_READ;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 75 "compiler.l"
{PRINT_TOK(P_WRITE); return P_WRITE;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 76 "compiler.l"
{PRINT_TOK(P_BCONST); return P_BCONST;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 77 "compiler.l"
{PRINT_TOK(P_BCONST); return P_BCONST;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 79 "compiler.l"
{PRINT_TOK(P_CCONST); return P_CCONST;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 80 "compiler.l"
{PRINT_TOK(P_CCONST); return P_CCONST;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 82 "compiler.l"
{PRINT_TOK(P_CCONST); return P_CCONST;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 83 "compiler.l"
{PRINT_TOK(P_CCONST); return P_CCONST;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 84 "compiler.l"
{PRINT_TOK(P_CCONST); return P_CCONST;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 85 "compiler.l"
{PRINT_TOK(P_CCONST); return P_CCONST;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 86 "compiler.l"
{PRINT_TOK(P_CCONST); return P_CCONST;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 87 "compiler.l"
{PRINT_TOK(P_CCONST); return P_CCONST;}
	YY_BREAK
/*TELESTES*/
case 38:
YY_RULE_SETUP
#line 90 "compiler.l"
{PRINT_TOK(P_RELOP); return P_RELOP;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 92 "compiler.l"
{PRINT_TOK(P_ADDOP); return P_ADDOP;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 94 "compiler.l"
{PRINT_TOK(P_OROP); return P_OROP;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 96 "compiler.l"
{PRINT_TOK(P_MULDIVANDOP); return P_MULDIVANDOP;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 98 "compiler.l"
{PRINT_TOK(P_NOTOP); return P_NOTOP;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 100 "compiler.l"
{PRINT_TOK(P_INOP); return P_INOP;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 103 "compiler.l"
{PRINT_TOK(P_ID); return P_ID;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 104 "compiler.l"
{PRINT_TOK(P_ICONST); return P_ICONST;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 105 "compiler.l"
{PRINT_TOK(P_RCONST); return P_RCONST;}
	YY_BREAK
/*ALLES LEKTIKES MONADES*/
case 47:
YY_RULE_SETUP
#line 110 "compiler.l"
{PRINT_TOK(P_LPAREN); return P_LPAREN;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 111 "compiler.l"
{PRINT_TOK(P_RPAREN); return P_RPAREN;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 112 "compiler.l"
{PRINT_TOK(P_SEMI); return P_SEMI;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 113 "compiler.l"
{PRINT_TOK(P_DOT); return P_DOT;} 
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 114 "compiler.l"
{PRINT_TOK(P_COMMA); return P_COMMA;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 115 "compiler.l"
{PRINT_TOK(P_EQU); return P_EQU;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 116 "compiler.l"
{PRINT_TOK(P_COLON); return P_COLON;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 117 "compiler.l"
{PRINT_TOK(P_LBRACK); return P_LBRACK;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 118 "compiler.l"
{PRINT_TOK(P_RBRACK); return P_RBRACK;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 119 "compiler.l"
{PRINT_TOK(P_ASSIGN); return P_ASSIGN;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 120 "compiler.l"
{PRINT_TOK(P_DOTDOT); return P_DOTDOT;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 121 "compiler.l"
{   }
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 122 "compiler.l"
{printf("Line: %d\n", yylineno);}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 123 "compiler.l"
{   }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 128 "compiler.l"
{BEGIN(COMMENTS);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 129 "compiler.l"
{BEGIN(INITIAL); printf(" Found comment returning: %d\n", P_COMM); return P_COMM;}
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 130 "compiler.l"
{   }
	YY_BREAK
case YY_STATE_EOF(COMMENTS):
#line 131 "compiler.l"
{printf("Unfinished Comment\n");}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 138 "compiler.l"
{BEGIN(PSTRING);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 139 "compiler.l"
{BEGIN(INITIAL); printf(" Found string returning: %d\n", P_SCONST); return P_SCONST;}
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 140 "compiler.l"
{printf("string new line\n");}
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 141 "compiler.l"
{   if (strlen(yytext) == 2){
                                if(strcmp(yytext, "\\n") == 0){
                                    strcat(str_buf, "\n");
                                }else if(strcmp(yytext, "\\t") == 0){
                                    strcat(str_buf, "\t");
                                }else if(strcmp(yytext, "\\f") == 0){
                                    strcat(str_buf, "\f");
                                }else if(strcmp(yytext, "\\r") == 0){
                                    strcat(str_buf, "\r");
                                }else if(strcmp(yytext, "\\b") == 0){
                                    strcat(str_buf, "\b");
                                }else if(strcmp(yytext, "\\v") == 0){
                                    strcat(str_buf, "\v");
                                }else{
                                    strcat(str_buf, &yytext[1]);
                                }

                            }else{
                                strcat(str_buf, yytext);
                            }
                        }
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 162 "compiler.l"
{printf("found new line\n");}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 163 "compiler.l"
{printf("unknown\n");}
	YY_BREAK
case YY_STATE_EOF(PSTRING):
#line 164 "compiler.l"
{printf("end of string without exiting it\n");}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 166 "compiler.l"
{printf("unknown\n");}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 167 "compiler.l"
{printf("Found End Of File returning: %d\nFile compiled successfully.\n", P_EOF); return P_EOF;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 171 "compiler.l"
ECHO;
	YY_BREAK
#line 1495 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 213 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 213 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 212);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 171 "compiler.l"


int main(int argc, char *argv[]){
    int token;
    if(argc > 1){
        yyin = fopen(argv[1], "r");
        if (yyin == NULL){
            perror ("Error");
            return -1;
        }
    }

    do{
        token = yylex();

    }while(token != 0);

    fclose(yyin);
    yyterminate();
}


void PRINT_TOK(int token_id){
    
    if(token_id == P_ICONST){
        printf("Found integer token '%s' with base 10: %d returning: %d at line %d\n", yytext, BINHEX_TO_INT(yytext), token_id, yylineno);
    }
    else if(token_id == P_RCONST){
        printf("Found float token '%s' with base 10: %.2f returning: %d at line %d\n", yytext, FBINHEX_TO_FLOAT(yytext), token_id, yylineno);

    }
    else{
        printf("Found token '%s' returning: %d at line: %d\n", yytext, token_id, yylineno);

    }
}

int BINHEX_TO_INT(char *str){
    if(strncmp(str, "0B", 2) == 0){
        return (int) strtoll(&str[2], NULL, 2);
    }
    else if(strncmp(str, "0H", 2) == 0){
        return (int) strtoll(&str[2], NULL, 16);
    }
    else{
        return (int) strtoll(str, NULL, 10);
    }

}

float FBINHEX_TO_FLOAT(char *str){
    if(strncmp(str, "0B", 2) == 0){
        float number = 0.0;
        int i,length_real;
        char *character;
        character = strchr(str,'.');
        length_real = strlen(character)-1;
        number = (int)strtol(&str[2],&character,2);
        for(i=1;i<=length_real;i++){
            number += (character[i] - '0') * (1/pow(2,i));
    }
        return number;    
    }
    else if(strncmp(str, "0H", 2) == 0){
        float number = 0.0;
        int i,length_real;
        char *character;
        character = strchr(str,'.');
        length_real = strlen(character)-1;
        number = (int)strtol(&str[2],&character,16);
        for(i=1;i<=length_real;i++){
            if(character[i] <= '9')
    			number += (character[i] - '0') * (1/pow(16,i));
    		else
    			number += (character[i] + 10 - 'A') * (1/pow(16,i));
    	}
        return number;
     }else{
        float number = atof(yytext);
        return number;
    } 
}

void yyerror(const char* err){
    errorCnt++;
    printf("[error - line: %d] %s\n", yylineno, err);

    if(errorCnt == 5){
        printf("Errors found max\n");
        exit(EXIT_FAILURE);
    }
    yyless(1);
}

    
